on:
  push:
  pull_request:
  schedule:
    - cron: '45 3 * * 3'

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.8'
          - '3.9'
          - '3.10'
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install requests
      - name: Run tests
        run: python test.py

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build \
            --no-cache \
            -t dbrgn/churz:latest \
            -t dbrgn/churz:1 \
            .
      - name: Push Docker image
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" && \
          docker push dbrgn/churz:latest && \
          docker push dbrgn/churz:1
